version: '3.9'

services:
  postgres:
    image: postgres:14.11
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /bober-db/data
    volumes:
      - .:/docker-entrypoint-initdb.d
      - boberdb-data:/
    ports:
      - ":"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  -d "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  server-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=

volumes:
  boberdb-data:
  server-backend:
